### ISSUE TITLE
Sample Training Data

### ISSUE THREAD

**Issue by MarkLoukko** [sparalic/Predicting-future-medical-diagnoses-with-RNNs-using-Fast-AI-API-from-scratch#1]
Hi Sparkle,

I've been trying to run your code but I'm having an issue.  "for x, y in train_dl:" is not looping in the "Training and validation loop" section. I think it has to do with the file I'm sending to load_data(). Could you upload a small sample of your Jan19.seqs file? Or any sequence file that works?

Cheers
Mark

**Comment by sparalic** [comment]
Added Jan.seqs file
